import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./contexts/ThemeContext";

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Portfolio-Fian",
  description: "Generated by create next app",
=======
  title: "Fian Kurniawan - Web Developer",
  description: "Fian Kurniawan | Portofolio",
>>>>>>> 5873b93 (up)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
