name: Deploy to Vercel

on:
  push:
    branches:
      - Main

jobs:
  deploy:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install --global vercel

      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
# AMBIL SECRET TOKEN
# 1. kowe ambil SECRET TOKEN DI = https://vercel.com/account/settings/tokens
# 2. buat TOKEN NAME = VERCEL_TOKEN
# 3. SCOPE ITU AKUN KOWE
# 4. EXPIRATION BISA PERMANENT KALAU 1 Year BAGUSAN PERMANENT

# GITHUB CARA MASUKIN SECRET TOKEN TANPA PERLU ENV
# 1.BUAT REPOSITORY
# 2.KE SETTING REPOSITORY
# 3.CARI secrets and variables
# 4.DIBAGIAN ACTION ADA NEW REPOSITORY
# 5.MASUKIN VERCEL_TOKEN DI MASUKIN SECRET KEY LU DI VALUE TEXTAREANYA ABIS ITU UDAH TINGGAL ACCEPT

# MENGGUNAKAN GITHUB WORKFLOW BUAT MENERAPKAN DEPLOYMENT SECARA OTOMATIS
# 1.KARENA DISINI SUDAH ADA FOLDER .github/workflows ada file yang bernama cd.yml dan ci.yml
# 2.dibagian repository ada yang bernama actions run disitu cd.yml
# 3. pastikan vercel_token sudah di masukan di settingan kowe
# 4. kalau sudah silahkan running cd.yml melalui github atau ekteksion github action
# 5. jika tanda ya hijau berarti deploy men sudah berhasil jika tanda merah berarti ada error yang terjadi pastikan dibaca
# 6. ke vercel untuk melihat hasil apakah sudah ke deploy dengan baik

# INI TESTING BISA WINDOWS MACOS DAN LINUX
